name: go-live
version: '1.2.0'
summary: A very lightweight CLI utility to start serving a file directory
description: |
  go-live can be used for local web development, production static-site serving, or as a network file server. By default go-live serves the directory it is executed in.

license: Apache-2.0
base: core20
icon: logo.png
grade: stable
confinement: strict
architectures:
  - "i386"
  - amd64
  - armhf
  - arm64
 
apps:
  go-live:
    command: bin/go-live
    plugs:
      - home
      - network
      - network-bind
      - removable-media

parts:
  go-live:
    plugin: go
    go-channel: 1.21/stable
    source: .
    source-type: git
